version: "3"

services:
  database-gamification-engine:
    image: postgres:alpine
    restart: always
    expose:
      - 11032
    ports:
      - "11032:5432"
    volumes:
      - templatedata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gamificationengine
  app-gamification-engine:
    build:
      context: ./../gamification_engine # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: gamification_engine
    expose:
      - 11000
      - 11001
    ports:
      - "11000:11000"
      - "11001:11001"
    depends_on:
      - database-gamification-engine
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-template:5432/gamificationengine
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-template:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "gamification_engine",
      "--app-port", "11001",
      "--dapr-http-port", "11000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../gamification-engine/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-gamification-engine
      - redis
    network_mode: "service:app-gamification-engine"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  templatedata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true