name: Testing CI pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: rulesengine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: cleanTest test
# Configuration for SonarCloud, enable this when SonarCloud is configured
#      - name: Execute tests
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        uses: gradle/gradle-build-action@v3
#        with:
#          arguments: cleanTest test jacocoTestReport sonar





